### ISSUE TITLE
Armor Bar position doesn't adjust if you have more than one row of hearts.

### ISSUE THREAD

**Issue by MLMII** [LocusWay/OverpoweredArmorBar#1]
If you have multiple layers of hearts, whether that is from absorption, or a mod that simply gives you extra hearts the armor bar doesn't adjust upwards like the unmodded armor bar does.

**Comment by LocusWay** [comment]
I have hopefully fixed the bug where the absorption bar was not taken into account with version 1.12.2-0.2.1

Supporting UI changes from other mods is likely a complicated issue, as I would need to know details of how the mod is changing the UI and possibly the settings used by that mod if some adjustments are optional.
I believe this could require changes to both my mod and theirs (if i need to request configuration information from them) That is a level of complexity I don't feel is justified at the moment for this mod.
