### ISSUE TITLE
Double bar

### ISSUE THREAD

**Issue by Ash70** [LocusWay/OverpoweredArmorBar#11]
Not really a bug, but there is another mod (I think cyclic, or perhaps thaumcraft?) that adds a second armor bar to the display. This second bar does not get removed when using your mod. Is this something you can correct or should I ask the author of the other mod to include an option?
![armorbar](https://user-images.githubusercontent.com/22838247/45287438-9630e800-b4e8-11e8-96ae-3d5e389f2c51.png)

**Comment by yikies** [comment]
its rustic, there is a config option

**Comment by Ash70** [comment]
So it is. Thank you.
