### ISSUE TITLE
Conflict with mekanism?

### ISSUE THREAD

**Issue by beanaboston** [LocusWay/OverpoweredArmorBar#4]
Your mod seems to conflict with mekanism in some way. When wearing the armored jetpack (has more defense than diamond) it says it gives no defense. But seems just to be a visual glitch. I can provide screenshots if you'd like, but it basically just makes the armor bar say it gives no defense, but it definitely was giving me defense.
mod list: modlister.com/beanaboston

**Comment by LocusWay** [comment]
I've had a look at it and it seems like the Mekanism Armored Jetpack doesn't have an armor value set in the traditional way.
This is shown as the following in the mouse over tooltip.
e.g Diamond armor has
When on body:
+2 Armor Toughness
+8 Armor
This will be why the armor value isn't showing up. 

I'm unsure how the vanilla armor bar is changing when the armored jetpack is worn.

**Comment by beanaboston** [comment]
Dunno. Works with just mekanism and works with the rest of my mods except
your mod. Don't know if you'll even be able to fix it but eh. At least
you're aware.

**Comment by LocusWay** [comment]
I've just uploaded v0.2.2 with a hopeful fix for the issue. It works for me for the armored jetpack but may have issues in other situations.
