### ISSUE TITLE
If you have more than 10 hearts (absorption or red) they get covered by the armor bar

### ISSUE THREAD

**Issue by PrinceOfAmber** [LocusWay/OverpoweredArmorBar#6]
In vanilla, the armor bar gets pushed up by the hearts, with this mod it does not

**Comment by LocusWay** [comment]
There isn't enough information in this report for me to be able to reproduce this.
This mod doesn't support other mods adjusting the health bar. It has no way of knowing it is happening as as you've seen overlaps.
It is noted in the readme, but not on the Twitch Page.I've updated the Twitch page to reflect that limitation.

My testing was done using golden apples which do correctly move the armor bar.

**Comment by LocusWay** [comment]
I've uploaded 0.3.0 as an alpha build, let me know if this solves the issue.
